Connect API
TayyabKM/Bookstore pull request #4
Opened 2023-03-10 07:43 UTC by TayyabKM

### Following tasks were completed:

- Fix linter errors.
-  Refactor add book and remove book features to persist changes in the server.
-  Fetched book list from Bookstore API.

2023-03-10 08:08 UTC, danmainah requested changes
Hi @TayyabKM , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Gitflow was correctly used
✔️  Good design


# Required Changes ♻️

- [ ] @TayyabKM kindly ensure your categories page is working am getting a black page as shown below 
![image](https://user-images.githubusercontent.com/61408860/224258995-dd8cc8ec-5241-4eb5-8e9c-e35189b4e552.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-10 08:08 UTC, danmainah commented on README.md
>  > Describe between 1-3 key features of the application.
- [x] @TayyabKM kindly remove the instruction description message in the key features and future features section as they are supposed to guide you when creating the readme and should be deleted afterward.
- [x] Kindly ensure your live demo link is working correctly , its good practise having all your links work properly

2023-03-10 08:08 UTC, danmainah commented on src/components/API/API.js
> +/* eslint-disable linebreak-style */
- [x] @TayyabKM it's not good to practice disabling the linter check in your file, kindy try and fix the errors instead of disabling the linter check.

2023-03-10 08:08 UTC, danmainah commented on src/components/Addbook/AddingBooks.js
> +/* eslint-disable import/no-extraneous-dependencies */
- [x] @TayyabKM it's not good to practice disabling the linter check in your file, kindy try and fix the errors instead of disabling the linter check.

2023-03-10 08:08 UTC, danmainah commented on src/redux/books/books.js
> +      // eslint-disable-next-line no-param-reassign
- [ ] @TayyabKM it's not good to practice disabling the linter check in your file, kindy try and fix the errors before disabling the linter check.

2023-03-10 08:08 UTC, danmainah commented on src/redux/books/books.js
> +      // eslint-disable-next-line no-param-reassign
- [ ] @TayyabKM it's not good to practice disabling the linter check in your file, kindy try and fix the errors before disabling the linter check.

2023-03-10 14:06 UTC, DammyShittu approved these changes
Hi @TayyabKM,

## APPROVED 🟢

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-10 14:12 UTC, merged

2023-05-08 14:51 UTC, Abenezer-Tilahun reviewed
Hi @TayyabKM 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git-Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️ Good job for Implemented Bookstore: connect to API.

## Optional suggestions 
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._